#网站配置
website:
  #网站名
  name: Bookstore Online
  #域名
  domain: www.xxyopen.com
  #SEO关键词
  keyword: ${website.name}, novel, online book store, online reading, original literature system, free novel building procedures
  #SEO描述
  description: ${website.name}is a multi-end (PC, WAP) reading, functional original literature CMS system, by the front portal system, writer background management system, platform background management system, crawler management system and other subsystems, support member recharge, subscription mode, news release and real-time statistical reports and other functions, new books automatically enter the library, old books automatically update.
  #联系QQ
  qq:
